Repository bradylangdale/Chromatose, pull requests merged in 2023-04, with the labels that each got.

#52 Add the new map and turned on bloom
  main.py
  playercontroller.py
Labels: graphical-asset, gameplay

#57 Fix jumping and adjust shaders
  main.py
  playercontroller.py
Labels: gameplay

#56 Adds Pause menu
  main.py
  pausemenu.py
  playercontroller.py
Labels: ui

#65 Add crystals class
  crystalobject.py
  main.py
Labels: gameplay

#68 Add enemies billboards
  main.py
Labels: graphical-asset, gameplay

#74 Adds Color meters
  playercontroller.py
  verticalbar.py
Labels: ui
