Repository bradylangdale/Chromatose, pull requests merged in 2023-03, with the labels that each got.

#24 Add dynamic physics object loading
  EstesV2.mtl
  EstesV2.obj
  interactableobject.py
  isosphere.mtl
  isosphere.obj
  main.py
  playercontroller.py
Labels: physics

#25 Add dynamic shader code
  main.py
  playercontroller.py
  shaders/colors.frag
  shaders/colors.vert
Labels: base-mechanic, gameplay

#35 Adds BillboardObject and temporary sprite sprite.png to test it
  billboardobject.py
  main.py
  sprite.png
Labels: base-mechanic

#39 Add lighting support
  Assets/assets/Map/Map.blend
  Assets/assets/Map/Map.blend1
  Assets/assets/Map/Map2.glb
  billboardobject.py
  interactableobject.py
  main.py
  pipeline.py
Labels: base-mechanic, gameplay

#40 Add gun to player model
  main.py
  playercontroller.py
Labels: graphical-asset, gameplay

#42 Fix objects falling through
  interactableobject.py
  main.py
Labels: bug

#43 Improve player controller
  billboardobject.py
  interactableobject.py
  main.py
  playercontroller.py
Labels: enhancement, base-mechanic, physics

#44 Add ability to go fullscreen
  main.py
  pipeline.py
  playercontroller.py
Labels: graphical-asset

#46 Add ability to pick up crystals
  interactableobject.py
  main.py
  playercontroller.py
Labels: base-mechanic, gameplay
